# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: service.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\"!\n\x0eMessageRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\"#\n\x0fMessageResponse\x12\x10\n\x08response\x18\x01 \x01(\t\"\xa1\x01\n\x06\x43ompra\x12\x17\n\x0fnombre_producto\x18\x01 \x01(\t\x12\x0e\n\x06precio\x18\x02 \x01(\x01\x12\x15\n\rpasarela_pago\x18\x03 \x01(\t\x12\x15\n\rmarca_tarjeta\x18\x04 \x01(\t\x12\r\n\x05\x62\x61nco\x18\x05 \x01(\t\x12\x0e\n\x06region\x18\x06 \x01(\t\x12\x11\n\tdireccion\x18\x07 \x01(\t\x12\x0e\n\x06\x63orreo\x18\x08 \x01(\t2f\n\tMyService\x12\x30\n\x0bSendMessage\x12\x0f.MessageRequest\x1a\x10.MessageResponse\x12\'\n\nSendCompra\x12\x07.Compra\x1a\x10.MessageResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MESSAGEREQUEST']._serialized_start=17
  _globals['_MESSAGEREQUEST']._serialized_end=50
  _globals['_MESSAGERESPONSE']._serialized_start=52
  _globals['_MESSAGERESPONSE']._serialized_end=87
  _globals['_COMPRA']._serialized_start=90
  _globals['_COMPRA']._serialized_end=251
  _globals['_MYSERVICE']._serialized_start=253
  _globals['_MYSERVICE']._serialized_end=355
# @@protoc_insertion_point(module_scope)
